name: formula_one
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  flutter_svg: ^2.0.9
  go_router: ^4.2.2
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  kartal: ^2.3.2
  mobx: ^2.0.7+5
  vexana: ^2.8.1

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true
  assets:
    - asset/image/
    - asset/svg/
    - asset/lang/
    - asset/lottie/
